module.exports = {
"15842": { name: "Ipung Suseno", position: "Sales Advisor", store: "Serpong, Tangerang", password: null, active: true },
      "15858": { name: "Mahendra Nurmadani", position: "Sales Advisor", store: "Lippo Mall Puri", password: null, active: true },
      "15860": { name: "Ahmad Faiq Al Mamduh", position: "Sales Advisor", store: "Living World, Cibubur", password: null, active: true },
      "15900": { name: "Farel Pranata", position: "Sales Advisor", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "15984": { name: "Bayu Pamungkas", position: "Sales Advisor", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "17266": { name: "Muhammad Ilham Fajar", position: "Sales Advisor", store: "Pakuwon City Mall, Surabaya", password: null, active: true },
      "17346": { name: "Miftakhul Huda", position: "Sales Advisor", store: "Pakuwon Mall, Surabaya", password: null, active: true },
      "17590": { name: "Dilova Ayu Sang Latifa", position: "Sales Advisor", store: "Mall Metropolitan, Bekasi", password: null, active: true },
      "17682": { name: "Nunung Halimah", position: "Sales Advisor", store: "Tunjungan Plaza, Surabaya", password: null, active: true },
      "17683": { name: "Ananda Eka M", position: "Sales Advisor", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "17685": { name: "Amelia Eka Putri", position: "Sales Advisor", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "17704": { name: "Andry Hibriyanto", position: "Security Retail", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "17705": { name: "Fendi Prasetyo", position: "Security Retail", store: "Mayjend Jonosewojo, Surabaya", password: null, active: true },
      "17707": { name: "Garnish Larasaty", position: "Store Leader", store: "Tunjungan Plaza, Surabaya", password: null, active: true },
      "17729": { name: "Maharani Vivia Anggraini", position: "Sales Advisor", store: "Tunjungan Plaza, Surabaya", password: null, active: true },
      "17730": { name: "Safira Frida", position: "Sales Advisor", store: "Pakuwon City Mall, Surabaya", password: null, active: true },
      "17732": { name: "Muchammad Adam", position: "Security Retail", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "17746": { name: "Erista Eviani", position: "Sales Advisor", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "17759": { name: "Fitri Aulia Saadha", position: "Sales Advisor", store: "Mayjend Jonosewojo, Surabaya", password: null, active: true },
      "17778": { name: "Rahmawati", position: "Sales Advisor", store: "Pakuwon City Mall, Surabaya", password: null, active: true },
      "17783": { name: "Chia Vebianti", position: "Sales Advisor", store: "Pakuwon Mall, Surabaya", password: null, active: true },
      "17845": { name: "Wildan Fajar", position: "Sales Advisor", store: "Tunjungan Plaza, Surabaya", password: null, active: true },
      "17855": { name: "Moch. Munfarid Anwar", position: "Security Retail", store: "Tunjungan Plaza, Surabaya", password: null, active: true },
      "17874": { name: "Gita Venia Sedi", position: "Sales Advisor", store: "Pakuwon City Mall, Surabaya", password: null, active: true },
      "17875": { name: "Maria Erica S", position: "Sales Advisor", store: "Mall Metropolitan, Bekasi", password: null, active: true },
      "17913": { name: "Muhammad Ainurrofi", position: "Security Retail", store: "Pakuwon Mall, Surabaya", password: null, active: true },
      "17930": { name: "Ayu Ratnasari", position: "Sales Advisor", store: "Puri Indah Mall Jakarta", password: null, active: true },
      "17936": { name: "Ade Saepul Mubarok", position: "Sales Advisor", store: "Plaza Blok M", password: null, active: true },
      "17943": { name: "Virda Mikassara", position: "Sales Advisor", store: "Pakuwon Mall, Surabaya", password: null, active: true },
      "17963": { name: "Salwa Putri Priyanii", position: "Sales Advisor", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "17974": { name: "Nurhasan", position: "Security Retail", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "17987": { name: "Sam Nur Anto", position: "Security Retail", store: "Mall Metropolitan, Bekasi", password: null, active: true },
      "18006": { name: "Andri Yanuar A", position: "Sales Advisor", store: "Pakuwon Mall, Surabaya", password: null, active: true },
      "18025": { name: "R. Tubagus Permana", position: "Security Retail", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "18032": { name: "Abraham Suluh Satria Putra", position: "Sales Advisor", store: "Pakuwon City Mall, Surabaya", password: null, active: true },
      "18040": { name: "Lucky Firmansyah", position: "Sales Advisor", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "18041": { name: "Raffa Shafy Rizfalah", position: "Sales Advisor", store: "Cibinong City Mall", password: null, active: true },
      "18042": { name: "Syamsibar", position: "Security Retail", store: "Mall Metropolitan, Bekasi", password: null, active: true },
      "18064": { name: "Amalia Riska", position: "Sales Advisor", store: "Pakuwon City Mall, Surabaya", password: null, active: true },
      "18071": { name: "Annisa Nur Aini Syifa", position: "Sales Advisor", store: "Epicentrum Walk, Jakarta", password: null, active: true },
      "18127": { name: "Tama Burnama", position: "Security Retail", store: "Serpong, Tangerang", password: null, active: true },
      "18180": { name: "Moch. Fahmi", position: "Security Retail", store: "Pakuwon City Mall, Surabaya", password: null, active: true },
      "18193": { name: "Azzahra Maurentia Z", position: "Sales Advisor", store: "Pakuwon Mall, Surabaya", password: null, active: true },
      "18219": { name: "Franciska Ayu P", position: "Sales Advisor", store: "Pakuwon Mall, Surabaya", password: null, active: true },
      "18230": { name: "Dandi Saputra", position: "Sales Advisor", store: "Serpong, Tangerang", password: null, active: true },
      "18242": { name: "Anifah Pristia", position: "Sales Advisor", store: "Mayjend Jonosewojo, Surabaya", password: null, active: true },
      "18266": { name: "Muhammad Faisal", position: "Security Retail", store: "Pakuwon City Mall, Surabaya", password: null, active: true },
      "18274": { name: "Adi Maryadi", position: "Sales Advisor", store: "Puri Indah Mall Jakarta", password: null, active: true },
      "18276": { name: "Nataniel", position: "Sales Advisor", store: "AEON, BSD", password: null, active: true },
      "18277": { name: "Holy N.R.", position: "Sales Advisor", store: "Serpong, Tangerang", password: null, active: true },
      "18278": { name: "Kharisma Putra", position: "Sales Advisor", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "18279": { name: "Lydia Paulina S", position: "Sales Advisor", store: "Mayjend Jonosewojo, Surabaya", password: null, active: true },
      "18282": { name: "Shella Izhatul", position: "Sales Advisor", store: "Mayjend Jonosewojo, Surabaya", password: null, active: true },
      "18313": { name: "Dimas Aditama", position: "Sales Advisor", store: "Mayjend Jonosewojo, Surabaya", password: null, active: true },
      "18315": { name: "Lellyta Agesti", position: "Sales Advisor", store: "Tunjungan Plaza, Surabaya", password: null, active: true },
      "18316": { name: "Yufan Irsahufany", position: "Store Leader", store: "Mayjend Jonosewojo, Surabaya", password: null, active: true },
      "18318": { name: "Tati Almira", position: "Sales Advisor", store: "Summarecon Bekasi", password: null, active: true },
      "18318B": { name: "Puspa Dewi Ariani", position: "Sales Advisor", store: "Resinda Park Mall, Karawang", password: null, active: true },
      "18377": { name: "Dede Galih Wijaya", position: "Sales Advisor", store: "Living World, Cibubur", password: null, active: true },
      "18378": { name: "Faldy Septiyan P", position: "Sales Advisor", store: "Living World, Cibubur", password: null, active: true },
      "18379": { name: "Fonliana Gunawan", position: "Sales Advisor", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "18380": { name: "Jellyn Dian Tre Umami", position: "Sales Advisor", store: "Kota Kasablanka", password: null, active: true },
      "18381": { name: "Rizkia Naurafadilah", position: "Sales Advisor", store: "23 Paskal Mall, Bandung", password: null, active: true },
      "18407": { name: "Muhammad Kilfan Drajat", position: "Security Retail", store: "23 Paskal Mall, Bandung", password: null, active: true },
      "18408": { name: "Rudy Irawan", position: "Security Retail", store: "Serpong, Tangerang", password: null, active: true },
      "18428": { name: "Elsa Aulia Ramadhani", position: "Sales Advisor", store: "23 Paskal Mall, Bandung", password: null, active: true },
      "18429": { name: "Dewi Puja Amelia", position: "Sales Advisor", store: "23 Paskal Mall, Bandung", password: null, active: true },
      "18431": { name: "Baiq Arining Puspita", position: "Sales Advisor", store: "Pakuwon Mall, Bekasi", password: null, active: true },
      "18432": { name: "Septiyani Nur Fitroh", position: "Sales Advisor", store: "Pakuwon Mall, Yogyakarta", password: null, active: true },
      "18433": { name: "Ida Astria Ningsih", position: "Sales Advisor", store: "Summarecon Bekasi", password: null, active: true },
      "18434": { name: "Deri Pratama Setia", position: "Security Retail", store: "Summarecon Bekasi", password: null, active: true },
      "18435": { name: "Bagus Wicaksono", position: "Security Retail", store: "Summarecon Bekasi", password: null, active: true },
      "18467": { name: "Wildan Riwanda Putra", position: "Store Leader", store: "Pakuwon Mall, Surabaya", password: null, active: true },
      "18468": { name: "Twis Karol Yoshepine", position: "Sales Advisor", store: "Pakuwon Mall, Bekasi", password: null, active: true },
      "18470": { name: "Syifa Nur Adila", position: "Sales Advisor", store: "Summarecon Bekasi", password: null, active: true },
      "18471": { name: "Calvin Kezia", position: "Sales Advisor", store: "Summarecon Bekasi", password: null, active: true },
      "18472": { name: "Nesa Natalie Sandane", position: "Sales Advisor", store: "Serpong, Tangerang", password: null, active: true },
      "18473": { name: "Desriana Pradipta", position: "Sales Advisor", store: "23 Paskal Mall, Bandung", password: null, active: true },
      "18474": { name: "Muhamad Rizki Yanuar Yusup", position: "Sales Advisor", store: "23 Paskal Mall, Bandung", password: null, active: true },
      "18480": { name: "Wahyu Anggara Rizky Pratama", position: "Security Retail", store: "Mayjend Jonosewojo, Surabaya", password: null, active: true },
      "18489": { name: "Imam Mubarok", position: "Store Leader", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "18490": { name: "Dimas Mohammad Hafidz", position: "Store Leader", store: "Pakuwon Mall, Solo", password: null, active: true },
      "18491": { name: "Chintia Bella", position: "Sales Advisor", store: "Mall Metropolitan, Bekasi", password: null, active: true },
      "18492": { name: "Roudlotul Awaliyah", position: "Sales Advisor", store: "Summarecon Bekasi", password: null, active: true },
      "18494": { name: "Cahyani Cyanega", position: "Store Leader", store: "Pakuwon Mall, Bekasi", password: null, active: true },
      "18519": { name: "Martini", position: "Sales Advisor", store: "Living World, Cibubur", password: null, active: true },
      "18522": { name: "Griety Chenny Maniku", position: "Sales Advisor", store: "Manado Town Square", password: null, active: true },
      "18523": { name: "Valentine Ester Tangkilisan", position: "Sales Advisor", store: "Manado Town Square", password: null, active: true },
      "18526": { name: "Vinny Veronica", position: "Sales Advisor", store: "Manado Town Square", password: null, active: true },
      "18527": { name: "Livia Cefildy Emor", position: "Sales Advisor", store: "Puri Indah Mall Jakarta", password: null, active: true },
      "18528": { name: "Injili Lidia Rosalina Mongkareng", position: "Sales Advisor", store: "Manado Town Square", password: null, active: true },
      "18529": { name: "Dhashilvan J J Colondam", position: "Sales Advisor", store: "Manado Town Square", password: null, active: true },
      "18530": { name: "Michael Fadhil Aryanto", position: "Sales Advisor", store: "Puri Indah Mall Jakarta", password: null, active: true },
      "18531": { name: "Retno Sari", position: "Sales Advisor", store: "Puri Indah Mall Jakarta", password: null, active: true },
      "18532": { name: "Agustina Romadhona Amelia", position: "Sales Advisor", store: "AEON, JGC", password: null, active: true },
      "18533": { name: "Farah Muhammad Nizar", position: "Security Retail", store: "Tunjungan Plaza, Surabaya", password: null, active: true },
      "18535": { name: "Ratu Ayu Anjani", position: "Sales Advisor", store: "AEON, JGC", password: null, active: true },
      "18536": { name: "Agrecia Fransiska Raya", position: "Sales Advisor", store: "Serpong, Tangerang", password: null, active: true },
      "18537": { name: "Fikri Ardiansyah", position: "Store Leader", store: "Living World, Cibubur", password: null, active: true },
      "18539": { name: "Septi Diana Sari", position: "Sales Advisor", store: "Icon Mall, Palembang", password: null, active: true },
      "18540": { name: "Nora Pariska", position: "Sales Advisor", store: "Icon Mall, Palembang", password: null, active: true },
      "18541": { name: "Muhamad Hafiz Akbar", position: "Sales Advisor", store: "Icon Mall, Palembang", password: null, active: true },
      "18542": { name: "Andi Rifky Pawiloi", position: "Sales Advisor", store: "AEON Deltamas, Cikarang", password: null, active: true },
      "18543": { name: "Dea Riski Hauladian", position: "Sales Advisor", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "18544": { name: "Muhamad Rifky Dzul Fahmi", position: "Sales Advisor", store: "AEON Deltamas, Cikarang", password: null, active: true },
      "18546": { name: "Fitriyana", position: "Sales Advisor", store: "AEON Deltamas, Cikarang", password: null, active: true },
      "18547": { name: "Raka Abror", position: "Sales Advisor", store: "Galaxy Mall, Surabaya", password: null, active: true },
      "18548": { name: "Jessica Ekatama", position: "Sales Advisor", store: "Cibinong City Mall", password: null, active: true },
      "18549": { name: "Steven Mandala Tua Samosir", position: "Sales Advisor", store: "Plaza Medan Fair, Medan", password: null, active: true },
      "18574": { name: "Mochamad Ardiansyah P.", position: "Store Leader", store: "23 Paskal Mall, Bandung", password: null, active: true },
      "18575": { name: "Riska Septia Sukarman", position: "Sales Advisor", store: "Pakuwon Mall, Bekasi", password: null, active: true },
      "18577": { name: "Alexander Bimo", position: "Store Leader", store: "Pakuwon Mall, Yogyakarta", password: null, active: true },
      "18578": { name: "Revy Ayundya", position: "Sales Advisor", store: "Pakuwon Mall, Yogyakarta", password: null, active: true },
      "18580": { name: "Agnes Cindy Boru Siboro", position: "Sales Advisor", store: "Pakuwon Mall, Solo", password: null, active: true },
      "18581": { name: "Ayu Silvia", position: "Sales Advisor", store: "Cibinong City Mall", password: null, active: true },
      "18583": { name: "Gina Kusniawati", position: "Sales Advisor", store: "Icon Mall, Palembang", password: null, active: true },
      "18592": { name: "Velony Audrinalin", position: "Sales Advisor", store: "Cibinong City Mall", password: null, active: true },
      "18625": { name: "Syaipul Syahputra", position: "Sales Advisor", store: "SKA Pekanbaru", password: null, active: true },
      "18626": { name: "Rony Pratama Putra", position: "Sales Advisor", store: "SKA Pekanbaru", password: null, active: true },
      "18629": { name: "Firly Rahmah Istigparin", position: "Sales Advisor", store: "AEON, BSD", password: null, active: true },
      "18630": { name: "Mario Jordi", position: "Sales Advisor", store: "AEON, BSD", password: null, active: true },
      "18631": { name: "Dwinda Indriyani Br Ginting", position: "Sales Advisor", store: "AEON, BSD", password: null, active: true },
      "18632": { name: "Amriyati", position: "Sales Advisor", store: "Mall Metropolitan, Bekasi", password: null, active: true },
      "18633": { name: "Muhammad Rizky Januar F", position: "Sales Advisor", store: "AEON, Sentul", password: null, active: true },
      "18634": { name: "Meisy Anggraini Putri", position: "Sales Advisor", store: "Central Park 2, Jakarta", password: null, active: true },
      "18635": { name: "Muhammad Raihan Nazhif", position: "Sales Advisor", store: "AEON, JGC", password: null, active: true },
      "18636": { name: "Hilda Auliya", position: "Sales Advisor", store: "Plaza Blok M", password: null, active: true },
      "18637": { name: "Virly Andriani", position: "Sales Advisor", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "18638": { name: "Firra Alisya", position: "Sales Advisor", store: "Plaza Blok M", password: null, active: true },
      "18640": { name: "Ade Rahmat", position: "Store Leader", store: "Central Park 2, Jakarta", password: null, active: true },
      "18641": { name: "Andri Dharmawan", position: "Sales Advisor", store: "Central Park 2, Jakarta", password: null, active: true },
      "18642": { name: "M. Dzaki Raflisyah", position: "Sales Advisor", store: "Central Park 2, Jakarta", password: null, active: true },
      "18643": { name: "Yuni Yuliani", position: "Sales Advisor", store: "Pakuwon Mall, Bekasi", password: null, active: true },
      "18644": { name: "Mutia Rahayu", position: "Sales Advisor", store: "Central Park 2, Jakarta", password: null, active: true },
      "18645": { name: "Indah Julianita", position: "Sales Advisor", store: "Resinda Park Mall, Karawang", password: null, active: true },
      "18646": { name: "Eka Nurhayati", position: "Sales Advisor", store: "Supermall, Karawaci", password: null, active: true },
      "18647": { name: "Nur Bayinah", position: "Sales Advisor", store: "Supermall, Karawaci", password: null, active: true },
      "18649": { name: "Septiana Ningrum", position: "Sales Advisor", store: "Pakuwon Mall, Solo", password: null, active: true },
      "18651": { name: "Regina Dara Calista", position: "Sales Advisor", store: "Pakuwon Mall, Yogyakarta", password: null, active: true },
      "18660": { name: "Harcahyani Alifia Ulfah", position: "Sales Advisor", store: "Plaza Blok M", password: null, active: true },
      "18661": { name: "Alief Eva Rizkiyanah", position: "Sales Advisor", store: "AEON, BSD", password: null, active: true },
      "18662": { name: "Marla Anggraeny", position: "Sales Advisor", store: "Cibinong City Mall", password: null, active: true },
      "18667": { name: "Diah Siti Hasanatul B.", position: "Sales Advisor", store: "Lippo Mall Puri", password: null, active: true },
      "18670": { name: "Rafli Darmawan", position: "Security Retail", store: "Puri Indah Mall Jakarta", password: null, active: true },
      "18690": { name: "Sandy Wijaya", position: "Security Retail", store: "Icon Mall, Palembang", password: null, active: true },
      "18693": { name: "Anggraeni Sandika", position: "Store Leader", store: "Mall Ciputra, Tangerang", password: null, active: true },
      "18694": { name: "Tarmiji Riyanto", position: "Store Leader", store: "Summarecon Bekasi", password: null, active: true },
      "18695": { name: "Bima Taqwa", position: "Store Leader", store: "Puri Indah Mall Jakarta", password: null, active: true },
      "18697": { name: "Viera Agustin", position: "Store Leader", store: "Cibinong City Mall", password: null, active: true },
      "18698": { name: "Muhamad Maulana Yusuf", position: "Store Leader", store: "AEON Deltamas, Cikarang", password: null, active: true },
      "18700": { name: "Hufron", position: "Sales Advisor", store: "Pakuwon Mall, Solo", password: null, active: true },
      "18701": { name: "Lisa Puspita Anggraini", position: "Sales Advisor", store: "Pakuwon Mall, Yogyakarta", password: null, active: true },
      "18702": { name: "Pipit Rahayu", position: "Sales Advisor", store: "Resinda Park Mall, Karawang", password: null, active: true },
      "18703": { name: "Dini Maulani", position: "Sales Advisor", store: "Resinda Park Mall, Karawang", password: null, active: true },
      "18706": { name: "Adinda Radifa", position: "Sales Advisor", store: "Tunjungan Plaza, Surabaya", password: null, active: true },
      "18708": { name: "Hengki Ferbriaman Zalukhu", position: "Sales Advisor", store: "AEON, Sentul", password: null, active: true },
      "18709": { name: "Syahdan Abu Syakir", position: "Sales Advisor", store: "AEON, Sentul", password: null, active: true },
      "18710": { name: "Rizky Fahmi Rizaldi", position: "Sales Advisor", store: "AEON, Sentul", password: null, active: true },
      "18711": { name: "Listiyan Wilda Sari", position: "Sales Advisor", store: "AEON, Sentul", password: null, active: true },
      "18713": { name: "Aulia Nurul Ghani", position: "Store Leader", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "18714": { name: "Cindyanta Maibang", position: "Store Leader", store: "Sun Plaza, Medan", password: null, active: true },
      "18715": { name: "Rania Febrini", position: "Sales Advisor", store: "Plaza Medan Fair, Medan", password: null, active: true },
      "18716": { name: "Asrul Hariadi", position: "Sales Advisor", store: "Plaza Medan Fair, Medan", password: null, active: true },
      "18717": { name: "Aldo Briliantano", position: "Sales Advisor", store: "Plaza Medan Fair, Medan", password: null, active: true },
      "18718": { name: "Naqiriziyani", position: "Sales Advisor", store: "Sun Plaza, Medan", password: null, active: true },
      "18719": { name: "Muhammad Rizal", position: "Sales Advisor", store: "Sun Plaza, Medan", password: null, active: true },
      "18720": { name: "Ayu Andira", position: "Sales Advisor", store: "Sun Plaza, Medan", password: null, active: true },
      "18722": { name: "Santi Yani Siregar", position: "Sales Advisor", store: "Supermall, Karawaci", password: null, active: true },
      "18723": { name: "Muhamad Hariri", position: "Sales Advisor", store: "Supermall, Karawaci", password: null, active: true },
      "18724": { name: "Winda Sari", position: "Sales Advisor", store: "AEON, BSD", password: null, active: true },
      "18726": { name: "Juhanna Fransiska", position: "Sales Advisor", store: "Lippo Mall Puri", password: null, active: true },
      "18727": { name: "Melfyana", position: "Sales Advisor", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "18728": { name: "Niken Zonitia", position: "Sales Advisor", store: "Central Park 2, Jakarta", password: null, active: true },
      "18729": { name: "Handika Aryadi", position: "Sales Advisor", store: "Lippo Mall Puri", password: null, active: true },
      "18737": { name: "Muhamad Syahroni", position: "Security Retail", store: "Supermall, Karawaci", password: null, active: true },
      "18742": { name: "Arham Nuriman", position: "Security Retail", store: "Central Park 2, Jakarta", password: null, active: true },
      "18743": { name: "Yasser Novanza", position: "Security Retail", store: "Cibinong City Mall", password: null, active: true },
      "18745": { name: "Taufik Hidayat", position: "Security Retail", store: "Icon Mall, Palembang", password: null, active: true },
      "18755": { name: "Dimas Darmawan", position: "Security Retail", store: "Pakuwon Mall, Solo", password: null, active: true },
      "18756": { name: "Arief Nur Hidayat", position: "Security Retail", store: "Pakuwon Mall, Solo", password: null, active: true },
      "18773": { name: "Eko Purwanto", position: "Security Retail", store: "Living World, Cibubur", password: null, active: true },
      "18786": { name: "Robby Tri Yanuar", position: "Security Retail", store: "23 Paskal Mall, Bandung", password: null, active: true },
      "18787": { name: "Tatang Gunawan", position: "Security Retail", store: "Pakuwon Mall, Yogyakarta", password: null, active: true },
      "18788": { name: "Taufan Kurniawan", position: "Security Retail", store: "Pakuwon Mall, Yogyakarta", password: null, active: true },
      "18790": { name: "Zikri Maulana", position: "Security Retail", store: "SKA Pekanbaru", password: null, active: true },
      "18792": { name: "Wahyu Santoso", position: "Store Leader", store: "Resinda Park Mall, Karawang", password: null, active: true },
      "18793": { name: "Eva Linda Pasaribu", position: "Store Leader", store: "Plaza Medan Fair, Medan", password: null, active: true },
      "18794": { name: "M Haeqal Phasa", position: "Store Leader", store: "Gandaria City", password: null, active: true },
      "18795": { name: "Firdaus Fajar Nugraha", position: "Sales Advisor", store: "Mall Metropolitan, Bekasi", password: null, active: true },
      "18796": { name: "Devi Rahmawati", position: "Sales Advisor", store: "Resinda Park Mall, Karawang", password: null, active: true },
      "18797": { name: "Nadifah Lailan", position: "Sales Advisor", store: "Plaza Medan Fair, Medan", password: null, active: true },
      "18798": { name: "Wahyu Ningsih", position: "Sales Advisor", store: "Sun Plaza, Medan", password: null, active: true },
      "18799": { name: "Deny Syahputra M", position: "Sales Advisor", store: "Sun Plaza, Medan", password: null, active: true },
      "18800": { name: "Citra Risxi Rahmadani", position: "Sales Advisor", store: "AEON, JGC", password: null, active: true },
      "18801": { name: "Titania Irmelda", position: "Sales Advisor", store: "AEON, JGC", password: null, active: true },
      "18802": { name: "Shopie Ahmad", position: "Sales Advisor", store: "Gandaria City", password: null, active: true },
      "18803": { name: "Rachica Pasha", position: "Sales Advisor", store: "Gandaria City", password: null, active: true },
      "18804": { name: "Deasy Fitriana Dewi", position: "Sales Advisor", store: "Gandaria City", password: null, active: true },
      "18805": { name: "Reva Aulia Rahmadani", position: "Sales Advisor", store: "SKA Pekanbaru", password: null, active: true },
      "18806": { name: "Doni As'Adi Elsa", position: "Sales Advisor", store: "Living World, Pekanbaru", password: null, active: true },
      "18807": { name: "M Fahri Nasution", position: "Sales Advisor", store: "Living World, Pekanbaru", password: null, active: true },
      "18808": { name: "Willy Octavianus Sitanggang", position: "Sales Advisor", store: "Living World, Pekanbaru", password: null, active: true },
      "18809": { name: "Arya Divo", position: "Sales Advisor", store: "Living World, Cibubur", password: null, active: true },
      "18810": { name: "Annisa Nabila", position: "Sales Advisor", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "18821": { name: "Aswin Dai", position: "Security Retail", store: "Manado Town Square", password: null, active: true },
      "18823": { name: "Erik Pratama", position: "Security Retail", store: "Plaza Medan Fair, Medan", password: null, active: true },
      "18851": { name: "Dwi Jaya Adhi Saputra", position: "Security Retail", store: "Living World, Cibubur", password: null, active: true },
      "18858": { name: "Elva Dewi Febriyani", position: "Store Leader", store: "Supermall, Karawaci", password: null, active: true },
      "18860": { name: "Evi Nispa Kristina Hondro", position: "Store Leader", store: "Living World, Pekanbaru", password: null, active: true },
      "18862": { name: "Annisa Prianti", position: "Sales Advisor", store: "Kota Kasablanka", password: null, active: true },
      "18863": { name: "Fillah Aziz Aldarini", position: "Sales Advisor", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "18864": { name: "Jonathan Owen", position: "Sales Advisor", store: "Tunjungan Plaza, Surabaya", password: null, active: true },
      "18865": { name: "Mila Tri Yunidhita", position: "Sales Advisor", store: "Gandaria City", password: null, active: true },
      "18866": { name: "Renna Pratiwi", position: "Sales Advisor", store: "Gandaria City", password: null, active: true },
      "18872": { name: "Nayla Ophelia", position: "Sales Advisor", store: "Pakuwon Mall, Solo", password: null, active: true },
      "18856": { name: "Janardi Sutono", position: "Area Manager", store: "", password: null, active: true },
      "18867": { name: "Indri Afni Cahya", position: "Sales Advisor", store: "Mall Of Serang", password: null, active: true },
      "18869": { name: "Nadya Mutiara", position: "Sales Advisor", store: "Mall Of Serang", password: null, active: true },
      "18870": { name: "Priyo Anggoro", position: "Sales Advisor", store: "Mall Of Serang", password: null, active: true },
      "18871": { name: "Steffany Clarinta Dwi", position: "Sales Advisor", store: "Mall Of Serang", password: null, active: true },
      "18888": { name: "Abdul Hakim", position: "Security Retail", store: "Cibinong City Mall", password: null, active: true },
      "18890": { name: "Ananda Rifal Saputra", position: "Security Retail", store: "Resinda Park Mall, Karawang", password: null, active: true },
      "18891": { name: "Galang Aji", position: "Security Retail", store: "Puri Indah Mall Jakarta", password: null, active: true },
      "18893": { name: "Aldi Renaldi", position: "Security Retail", store: "AEON Deltamas, Cikarang", password: null, active: true },
      "18951": { name: "Engkon Dea Mustika", position: "Sales Advisor", store: "Gandaria City", password: null, active: true },
      "18954": { name: "Lala Soleha", position: "Sales Advisor", store: "Kota Kasablanka", password: null, active: true },
      "18955": { name: "Reno Yurisman", position: "Sales Advisor", store: "Kota Kasablanka", password: null, active: true },
      "18956": { name: "Caroline Evelyna Sari", position: "Sales Advisor", store: "Central Park 2, Jakarta", password: null, active: true },
      "18957": { name: "Shifasa Sahara Aulia", position: "Sales Advisor", store: "Pakuwon Mall, Solo", password: null, active: true },
      "18952": { name: "Ilham Rheza", position: "Sales Advisor", store: "Lippo Mall Nusantara", password: null, active: true },
      "18953": { name: "Alda Devita Niansari", position: "Sales Advisor", store: "Mall Olimpic Garden, Malang", password: null, active: true },
      "18960": { name: "Indah Wati", position: "Sales Advisor", store: "Epicentrum Walk, Jakarta", password: null, active: true },
      "18961": { name: "Lenta Kristina Yanti", position: "Sales Advisor", store: "Epicentrum Walk, Jakarta", password: null, active: true },
      "18945": { name: "Yayan Uliyana", position: "Store Leader", store: "AEON, Sentul", password: null, active: true },
      "18946": { name: "Bryan Adam Priditama", position: "Store Leader", store: "Serpong, Tangerang", password: null, active: true },
      "18947": { name: "Yunita Virginia Mongkaren", position: "Store Leader", store: "Manado Town Square", password: null, active: true },
      "18948": { name: "Benny Arista", position: "Store Leader", store: "Kota Kasablanka", password: null, active: true },
      "18949": { name: "Movid Brigitta M.S", position: "Store Leader", store: "Mall Of Serang", password: null, active: true },
      "18958": { name: "Dio Ekananda Muharram", position: "Store Leader", store: "Epicentrum Walk, Jakarta", password: null, active: true },
      "18959": { name: "Bimo Bhakti Buana", position: "Store Leader", store: "Lippo Mall Kemang", password: null, active: true },
      "18970": { name: "Andriaman Purba", position: "Store Leader", store: "Lippo Mall Puri", password: null, active: true },
      "18989": { name: "Reza Eka Hendrawan", position: "Security Retail", store: "Lippo Mall Puri", password: null, active: true },
      "19013": { name: "Devitha Zaharani", position: "Sales Advisor", store: "Living World, Pekanbaru", password: null, active: true },
      "19014": { name: "Zains Ramadhan Salam", position: "Sales Advisor", store: "Lippo Mall Kemang", password: null, active: true },
      "19015": { name: "Cahyati", position: "Sales Advisor", store: "Lippo Mall Kemang", password: null, active: true },
      "19018": { name: "Yohanna Putri Auri Ellia Fransiska", position: "Sales Advisor", store: "Mall Ciputra, Tangerang", password: null, active: true },
      "19019": { name: "Jesica Salsabila Angel", position: "Sales Advisor", store: "Mall Ciputra, Tangerang", password: null, active: true },
      "19020": { name: "Namira Azzahrah Husnita", position: "Sales Advisor", store: "Mall Ciputra, Tangerang", password: null, active: true },
      "19023": { name: "Reza Aprilia Nadiah Saraswati", position: "Store Leader", store: "Lippo Mall Nusantara", password: null, active: true },
      "19010": { name: "Iftita Heryan Narulita", position: "Sales Advisor", store: "Mall Olimpic Garden, Malang", password: null, active: true },
      "19011": { name: "Anis Novitasari", position: "Sales Advisor", store: "Mall Olimpic Garden, Malang", password: null, active: true },
      "19012": { name: "Amara Winda", position: "Sales Advisor", store: "Mall Olimpic Garden, Malang", password: null, active: true },
      "19016": { name: "Endang Ismail", position: "Sales Advisor", store: "Mall Ciputra, Tangerang", password: null, active: true },
      "19017": { name: "Dinar Sunarya", position: "Sales Advisor", store: "Mall Ciputra, Tangerang", password: null, active: true },
      "19021": { name: "Hikmah Wahyuni", position: "Sales Advisor", store: "Epicentrum Walk, Jakarta", password: null, active: true },
      "19022": { name: "Yolanda Falty Lova", position: "Sales Advisor", store: "Epicentrum Walk, Jakarta", password: null, active: true },
      "19064": { name: "Deby Ningtias Wulandari", position: "Area Manager", store: "", password: null, active: true },
      "19090": { name: "Dila Ira Azura", position: "Sales Advisor", store: "Pondok Indah Mall, Jakarta", password: null, active: true },
      "19091": { name: "Aldi Revaldi", position: "Sales Advisor", store: "Serpong, Tangerang", password: null, active: true },
      "19077": { name: "Ahmad Syahroni", position: "Store Leader", store: "Icon Mall, Palembang", password: null, active: true },
      "19078": { name: "Brigita Ratnakanyaka Parardhya", position: "Store Leader", store: "Mall Ciputra Jakarta Grogol", password: null, active: true },
      "19083": { name: "Albany Nr", position: "Sales Advisor", store: "Lippo Mall Kemang", password: null, active: true },
      "19086": { name: "Muhammad Afdol", position: "Sales Advisor", store: "Lippo Mall Puri", password: null, active: true },
      "19092": { name: "Randa Junaidi", position: "Sales Advisor", store: "SKA Pekanbaru", password: null, active: true },
      "19082": { name: "Angelica Sihotang", position: "Sales Advisor", store: "Kota Kasablanka", password: null, active: true },
      "19081": { name: "Boi A Banjar Nahor", position: "Sales Advisor", store: "Pakuwon Mall, Bekasi", password: null, active: true },
      "19084": { name: "Christofer Reynara Eriesto", position: "Sales Advisor", store: "Lippo Mall Kemang", password: null, active: true },
      "19085": { name: "Rina Nur Hikmah", position: "Sales Advisor", store: "Lippo Mall Kemang", password: null, active: true }
};
